# Generated by Django 4.1.3 on 2022-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rhyme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rhymes", models.CharField(max_length=500)),
                ("patterns", models.CharField(max_length=1000)),
                ("part_speech", models.CharField(max_length=50)),
                ("score", models.IntegerField()),
            ],
        ),
    ]
