# Generated by Django 4.1.3 on 2022-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rhyme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhyme",
            name="patterns",
            field=models.JSONField(),
        ),
    ]
