# Generated by Django 4.1.3 on 2022-12-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rhyme", "0002_alter_rhyme_patterns"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhyme",
            name="word_with_stress",
            field=models.CharField(default="any stressed word", max_length=100),
        ),
        migrations.AddField(
            model_name="rhyme",
            name="word_without_stress",
            field=models.CharField(default="any unstressed word", max_length=100),
        ),
        migrations.AlterField(
            model_name="rhyme",
            name="part_speech",
            field=models.CharField(default="any part of speech", max_length=50),
        ),
        migrations.AlterField(
            model_name="rhyme",
            name="rhymes",
            field=models.TextField(default="tuple of rhymes", max_length=50000),
        ),
    ]
