# Generated by Django 4.1.7 on 2023-03-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0002_alter_word_stressed_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='stressed_word',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
