# Generated by Django 4.1.3 on 2022-12-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rhyme", "0003_rhyme_word_with_stress_rhyme_word_without_stress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhyme",
            name="depth_time",
            field=models.IntegerField(default=2),
        ),
    ]
