# Generated by Django 4.1.3 on 2022-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rhyme", "0004_rhyme_depth_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rhyme",
            old_name="patterns",
            new_name="pattern",
        ),
        migrations.RemoveField(
            model_name="rhyme",
            name="rhymes",
        ),
        migrations.AddField(
            model_name="rhyme",
            name="rhyme",
            field=models.CharField(default="any rhymed word", max_length=100),
        ),
    ]
