# Generated by Django 4.2 on 2023-04-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhyme', '0005_word_all_stresses_alter_word_stressed_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhymes',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhymes', to='rhyme.word'),
        ),
    ]
