version: '3.4'
services:
  web:
    container_name: django_rhyme
    build:
      context: .
    env_file:
        - .env
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    volumes:
      - static_volume_rhyme:/home/eugene/static
      - .:/home/eugene
  nginx:
    container_name: nginx_rhyme
    build:
      context: ./docker/nginx
    ports:
      - "8081:8081"
    volumes:
      - static_volume_rhyme:/home/eugene/static
    depends_on:
        - web
volumes:
    static_volume_rhyme:
