version: '3.4'
services:
  web:
    container_name: rhyme
    build:
      context: ./docker/python
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/home/eugene

