<<<<<<< HEAD
<<<<<<<< HEAD:docker-compose.prod.yaml
=======
>>>>>>> 3553f703e382e2fab61378fa69d1b3fcc4114bed
version: '3.4'
services:
  django_rhyme:
    image: eugene8pro/rhyme_for_web:latest
    env_file:
      - .env
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    volumes:
      - static_volume_rhyme:/home/eugene/static
  nginx:
    container_name: nginx_rhyme
    build:
      context: ./nginx_prod
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - ENV=production
    volumes:
      - static_volume_rhyme:/home/eugene/static
    depends_on:
      - django_rhyme
volumes:
  static_volume_rhyme:
<<<<<<< HEAD
========
version: '3.4'
services:
  web:
    container_name: django_rhyme_main
    build:
      context: .
    env_file:
        - ../.env
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    volumes:
      - static_volume_rhyme:/home/eugene/static
#      - .:/home/eugene
  nginx:
    container_name: nginx_rhyme
    build:
      context: ./nginx
    ports:
      - "8081:8081"
    volumes:
      - static_volume_rhyme:/home/eugene/static
    depends_on:
        - web
volumes:
    static_volume_rhyme:
>>>>>>>> 3553f703e382e2fab61378fa69d1b3fcc4114bed:myapp/docker-compose.yaml
=======
>>>>>>> 3553f703e382e2fab61378fa69d1b3fcc4114bed
