# Generated by Django 4.1.7 on 2023-03-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unstressed_word', models.CharField(max_length=500)),
                ('stressed_word', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rhymes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhyme', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('assonance', models.IntegerField()),
                ('pattern', models.JSONField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhyme.word')),
            ],
        ),
    ]
