version: '3.4'
services:
  web:
    container_name: django_rhyme_main
    build:
      context: .
    stdin_open: true
    tty: true
    env_file:
        - ../.env
    environment:
      - ENV=development
    ports:
      - "8000:8000"
    volumes:
      - static_volume_rhyme:/home/eugene/static
<<<<<<< HEAD
      - .:/home/eugene/

=======
#      - .:/home/eugene
>>>>>>> 3553f703e382e2fab61378fa69d1b3fcc4114bed
  nginx:
    container_name: nginx_rhyme
    build:
      context: ./nginx
    ports:
      - "8081:8081"
    volumes:
      - static_volume_rhyme:/home/eugene/static
    depends_on:
        - web
volumes:
    static_volume_rhyme:
